// app

export const GET_TOKEN_PENDING = 'GET_TOKEN_PENDING'
export const GET_TOKEN_SUCCESS = 'GET_TOKEN_SUCCESS'
export const GET_TOKEN_FAILURE = 'GET_TOKEN_FAILURE'

export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'

// api

export const GET_CONFIG_PENDING = 'GET_CONFIG_PENDING'
export const GET_CONFIG_SUCCESS = 'GET_CONFIG_SUCCESS'
export const GET_CONFIG_FAILURE = 'GET_CONFIG_FAILURE'

export const GET_USER_PENDING = 'GET_USER_PENDING'
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS'
export const GET_USER_FAILURE = 'GET_USER_FAILURE'

// github

export const GET_ALL_PENDING = 'GET_ALL_PENDING'
export const GET_ALL_SUCCESS = 'GET_ALL_SUCCESS'
export const GET_ALL_FAILURE = 'GET_ALL_FAILURE'

export const GET_PROFILE_PENDING = 'GET_PROFILE_PENDING'
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS'
export const GET_PROFILE_FAILURE = 'GET_PROFILE_FAILURE'

export const GET_UNREAD_PENDING = 'GET_UNREAD_PENDING'
export const GET_UNREAD_SUCCESS = 'GET_UNREAD_SUCCESS'
export const GET_UNREAD_FAILURE = 'GET_UNREAD_FAILURE'
