platform :ios, '9.0'

target 'GitHub' do
  pod 'React', path: '../node_modules/react-native', subspecs: %w[
    Core
    CxxBridge
    DevSupport
  ]

  pod 'yoga', path: '../node_modules/react-native/ReactCommon/yoga'

  pod 'DoubleConversion', podspec: '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'GLog', podspec: '../node_modules/react-native/third-party-podspecs/GLog.podspec'
  pod 'Folly', podspec: '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  pod 'Firebase/Core'
  pod 'Firebase/Messaging'

  pod 'SentryReactNative', path: '../node_modules/react-native-sentry'
end
